In [2]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('person.csv')

# Print the DataFrame
print(df)

C:\Users\W c\AppData\Local\Temp\ipykernel_15920\4077457104.py:4: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('person.csv')

       STATE STATENAME  ST_CASE  VEH_NO  PER_NO  VE_FORMS  COUNTY  MONTH
0          1   Alabama    10001       1       1         2     115      2  \
1          1   Alabama    10001       1       2         2     115      2
2          1   Alabama    10001       2       1         2     115      2
3          1   Alabama    10002       1       1         1      73      2
4          1   Alabama    10002       1       2         1      73      2
...      ...       ...      ...     ...     ...       ...     ...    ...
96742     56   Wyoming   560102       1       1         1      37     12
96743     56   Wyoming   560103       0       1         1      21     12
96744     56   Wyoming   560103       1       1         1      21     12
96745     56   Wyoming   560104       1       1         2      23     12
96746     56   Wyoming   560104       2       1         2      23     12

      MONTHNAME  DAY  ...  EMER_USE    EMER_USENAME ROLLOVER
0      February   12  ...       0.0  Not Applicable      0.0  \
1      February   12  ...       0.0  Not Applicable      0.0
2      February   12  ...       0.0  Not Applicable      0.0
3      February   11  ...       0.0  Not Applicable      0.0
4      February   11  ...       0.0  Not Applicable      0.0
...         ...  ...  ...       ...             ...      ...
96742  December   15  ...       0.0  Not Applicable      1.0
96743  December   19  ...       NaN             NaN      NaN
96744  December   19  ...       0.0  Not Applicable      0.0
96745  December   20  ...       0.0  Not Applicable      0.0
96746  December   20  ...       0.0  Not Applicable      0.0

                              ROLLOVERNAME IMPACT1     IMPACT1NAME FIRE_EXP
0                              No Rollover    12.0  12 Clock Point      0.0  \
1                              No Rollover    12.0  12 Clock Point      0.0
2                              No Rollover    12.0  12 Clock Point      0.0
3                              No Rollover    11.0  11 Clock Point      0.0
4                              No Rollover    11.0  11 Clock Point      0.0
...                                    ...     ...             ...      ...
96742  Rollover, Tripped by Object/Vehicle     0.0   Non-Collision      0.0
96743                                  NaN     NaN             NaN      NaN
96744                          No Rollover    12.0  12 Clock Point      0.0
96745                          No Rollover    12.0  12 Clock Point      0.0
96746                          No Rollover    12.0  12 Clock Point      0.0

             FIRE_EXPNAME  MAK_MOD
0      No or Not Reported   2407.0  \
1      No or Not Reported   2407.0
2      No or Not Reported  51404.0
3      No or Not Reported  59031.0
4      No or Not Reported  59031.0
...                   ...      ...
96742  No or Not Reported  82881.0
96743                 NaN      NaN
96744  No or Not Reported  34401.0
96745  No or Not Reported  48034.0
96746  No or Not Reported  49442.0

                                             MAK_MODNAME
0              Jeep / Kaiser-Jeep / Willys- Jeep Patriot
1              Jeep / Kaiser-Jeep / Willys- Jeep Patriot
2      Volvo XC60 (For 2019 on.  For model years 2008...
3                         Lexus ES-250/300/300h/330/ 350
4                         Lexus ES-250/300/300h/330/ 350
...                                                  ...
96742                    Freightliner Medium/Heavy - CBE
96743                                                NaN
96744  BMW X5 (For 2000-16.  For 2017 on, see model 4...
96745  Subaru Legacy/Outback(prior to 2003 only; see ...
96746                                      Toyota Sienna

[96747 rows x 126 columns]

In [1]:
df = df[df['SEX'] != 8]
df = df[df['SEX'] != 9]

NameError: name 'df' is not defined

In [4]:
df = df[df['PER_TYP'] == 1]

In [5]:
male_fatal = (df['SEX'] == 1) & (df['INJ_SEV'] == 4)
male_fatal.sum()

21329

In [6]:
df['SEX'].value_counts()

SEX
1    44036
2    15130
Name: count, dtype: int64

In [3]:
# Read the CSV file into a DataFrame
vl = pd.read_csv('violatn.csv')

# Print the DataFrame
print(vl)

       STATE STATENAME  ST_CASE  VEH_NO  VIOLATION VIOLATIONNAME
0          1   Alabama    10001       1          0           NaN
1          1   Alabama    10001       2          0           NaN
2          1   Alabama    10002       1          0           NaN
3          1   Alabama    10003       1          0           NaN
4          1   Alabama    10004       1          0           NaN
...      ...       ...      ...     ...        ...           ...
65526     56   Wyoming   560101       2          0           NaN
65527     56   Wyoming   560102       1          0           NaN
65528     56   Wyoming   560103       1          0           NaN
65529     56   Wyoming   560104       1          0           NaN
65530     56   Wyoming   560104       2          0           NaN

[65531 rows x 6 columns]

In [9]:
vl = vl[vl['VIOLATION'] != 0]

In [9]:
print(vl)

       STATE STATENAME  ST_CASE  VEH_NO  VIOLATION
14         1   Alabama    10010       1         95  \
15         1   Alabama    10010       2         71
20         1   Alabama    10013       1         75
59         1   Alabama    10042       1         95
71         1   Alabama    10051       1         72
...      ...       ...      ...     ...        ...
65498     56   Wyoming   560083       1         53
65501     56   Wyoming   560084       2         37
65507     56   Wyoming   560088       1         99
65512     56   Wyoming   560091       1         99
65523     56   Wyoming   560099       1          1

                                     VIOLATIONNAME
14     No Driver Present/Unknown if Driver Present
15                 Driving while license withdrawn
20                    Fail to carry insurance card
59     No Driver Present/Unknown if Driver Present
71                 Other driver license violations
...                                            ...
65498                     Improper, unsafe passing
65501                       Fail to obey stop sign
65507                         Unknown Violation(s)
65512                         Unknown Violation(s)
65523                     Manslaughter or homicide

[11144 rows x 6 columns]

In [66]:
df.to_csv("df.csv")

In [5]:
filtered_df = df.loc[:, ["ST_CASE", "VEH_NO", "HARM_EVNAME", "SEX", "SEXNAME", "PER_TYP", "PER_TYPNAME"]]
filtered_df.to_csv('filteredDF.csv')

In [68]:
df['SEX'].value_counts()

SEX
1    44036
2    15130
Name: count, dtype: int64

In [10]:
mergeddf = filtered_df.merge(vl, on="ST_CASE")

In [11]:
mergeddf[(mergeddf['SEX'] == 2) ]

,ST_CASE,VEH_NO_x,HARM_EVNAME,SEX,SEXNAME,PER_TYP,PER_TYPNAME,STATE,STATENAME,VEH_NO_y,VIOLATION,VIOLATIONNAME
0,10010,2,Motor Vehicle In-Transport,2,Female,1,Driver of a Motor Vehicle In-Transport,1,Alabama,1,95,No Driver Present/Unknown if Driver Present
1,10010,2,Motor Vehicle In-Transport,2,Female,1,Driver of a Motor Vehicle In-Transport,1,Alabama,2,71,Driving while license withdrawn
2,10010,2,Motor Vehicle In-Transport,2,Female,2,Passenger of a Motor Vehicle In-Transport,1,Alabama,1,95,No Driver Present/Unknown if Driver Present
3,10010,2,Motor Vehicle In-Transport,2,Female,2,Passenger of a Motor Vehicle In-Transport,1,Alabama,2,71,Driving while license withdrawn
7,10013,2,Motor Vehicle In-Transport,2,Female,1,Driver of a Motor Vehicle In-Transport,1,Alabama,1,75,Fail to carry insurance card
...,...,...,...,...,...,...,...,...,...,...,...,...
35240,560081,1,Guardrail Face,2,Female,2,Passenger of a Motor Vehicle In-Transport,56,Wyoming,1,4,"Inattentive, careless, improper driving, drivi..."
35242,560083,2,Motor Vehicle In-Transport,2,Female,1,Driver of a Motor Vehicle In-Transport,56,Wyoming,1,53,"Improper, unsafe passing"
35250,560091,1,Motor Vehicle In-Transport,2,Female,1,Driver of a Motor Vehicle In-Transport,56,Wyoming,1,99,Unknown Violation(s)
35253,560099,1,Pedestrian,2,Female,1,Driver of a Motor Vehicle In-Transport,56,Wyoming,1,1,Manslaughter or homicide
35254,560099,1,Pedestrian,2,Female,2,Passenger of a Motor Vehicle In-Transport,56,Wyoming,1,1,Manslaughter or homicide

In [12]:
mergeddf[(mergeddf['SEX'] == 1)]

,ST_CASE,VEH_NO_x,HARM_EVNAME,SEX,SEXNAME,PER_TYP,PER_TYPNAME,STATE,STATENAME,VEH_NO_y,VIOLATION,VIOLATIONNAME
4,10010,3,Motor Vehicle In-Transport,1,Male,1,Driver of a Motor Vehicle In-Transport,1,Alabama,1,95,No Driver Present/Unknown if Driver Present
5,10010,3,Motor Vehicle In-Transport,1,Male,1,Driver of a Motor Vehicle In-Transport,1,Alabama,2,71,Driving while license withdrawn
6,10013,1,Motor Vehicle In-Transport,1,Male,1,Driver of a Motor Vehicle In-Transport,1,Alabama,1,75,Fail to carry insurance card
8,10042,0,Motor Vehicle In-Transport,1,Male,5,Pedestrian,1,Alabama,1,95,No Driver Present/Unknown if Driver Present
15,10051,2,Ground,1,Male,1,Driver of a Motor Vehicle In-Transport,1,Alabama,1,72,Other driver license violations
...,...,...,...,...,...,...,...,...,...,...,...,...
35248,560088,1,Motor Vehicle In-Transport,1,Male,1,Driver of a Motor Vehicle In-Transport,56,Wyoming,1,99,Unknown Violation(s)
35249,560088,2,Motor Vehicle In-Transport,1,Male,1,Driver of a Motor Vehicle In-Transport,56,Wyoming,1,99,Unknown Violation(s)
35251,560091,2,Motor Vehicle In-Transport,1,Male,1,Driver of a Motor Vehicle In-Transport,56,Wyoming,1,99,Unknown Violation(s)
35252,560099,0,Pedestrian,1,Male,5,Pedestrian,56,Wyoming,1,1,Manslaughter or homicide
35255,560099,1,Pedestrian,1,Male,2,Passenger of a Motor Vehicle In-Transport,56,Wyoming,1,1,Manslaughter or homicide